In [1]:
import pandas as pd

In [2]:
datapath = "/home/black_tree/Desktop/NLP project /dataForFinetune.json"

In [3]:
import json

with open(datapath, "r") as f:
    df = json.load(f)

In [4]:
x = df["examples"]

In [5]:
data = pd.DataFrame(x)

In [6]:
data

,id,question,solution
0,example_1,"If 4x + i(3x – y) = 3 + i (– 6), where x and y...",We have 4x + i (3x – y) = 3 + i (–6). Equating...
1,example_2,Express the following in the form of a + bi: (...,(i) (−5i)(1/8 i) = -5/8 i² = -5/8(-1) = 5/8 = ...
2,example_3,Express (5 – 3i)³ in the form a + ib.,"We have, (5 – 3i)³ = 5³ – 3 × 5² × (3i) + 3 × ..."
3,example_4,Express (–√3 + √–2)(2√3 – i) in the form of a ...,"We have, (–√3 + √–2)(2√3 – i) = (–√3 + i√2)(2√..."
4,example_5,Find the multiplicative inverse of 2 – 3i.,Let z = 2 – 3i. Then z̄ = 2 + 3i and |z|² = 2²...
...,...,...,...
566,example_544,"If A = [[-2], [4], [5]] and B = [1, 3, -6], ve...","First, calculate AB = [[-2, -6, 12], [4, 12, -..."
567,example_545,"Express the matrix B = [[2, -2, -4], [-1, 3, 4...",Any square matrix B can be expressed as B = P ...
568,example_546,"If A = [[cosθ, sinθ], [-sinθ, cosθ]], prove by...",Base Case (n=1): The statement is true for n=1...
569,example_547,If A and B are symmetric matrices of the same ...,"Given A'=A and B'=B. First, assume AB is symme..."
570,example_548,"Let A=[[2,-1],[3,4]], B=[[5,2],[7,4]], C=[[2,5...","The equation is CD = AB. Let D=[[a,b],[c,d]]. ..."

In [7]:
data.drop("id", inplace= True, axis=1)

In [8]:
data.head()

,question,solution
0,"If 4x + i(3x – y) = 3 + i (– 6), where x and y...",We have 4x + i (3x – y) = 3 + i (–6). Equating...
1,Express the following in the form of a + bi: (...,(i) (−5i)(1/8 i) = -5/8 i² = -5/8(-1) = 5/8 = ...
2,Express (5 – 3i)³ in the form a + ib.,"We have, (5 – 3i)³ = 5³ – 3 × 5² × (3i) + 3 × ..."
3,Express (–√3 + √–2)(2√3 – i) in the form of a ...,"We have, (–√3 + √–2)(2√3 – i) = (–√3 + i√2)(2√..."
4,Find the multiplicative inverse of 2 – 3i.,Let z = 2 – 3i. Then z̄ = 2 + 3i and |z|² = 2²...

In [9]:
print(data["question"][0],"\n", data["solution"][0])

If 4x + i(3x – y) = 3 + i (– 6), where x and y are real numbers, then find the values of x and y.
 We have 4x + i (3x – y) = 3 + i (–6). Equating the real and the imaginary parts, we get 4x = 3 and 3x – y = – 6. On solving simultaneously, we get x = 3/4 and y = 33/4.

In [10]:
def format(d):
    x = d.iloc[0]
    y = d.iloc[1]
    z = f"### question: {x}  ### answer: {y}"
    return z

In [11]:
prompt = data.apply(format,axis= 1)

In [12]:
prompt.shape
prompt

0      ### question: If 4x + i(3x – y) = 3 + i (– 6),...
1      ### question: Express the following in the for...
2      ### question: Express (5 – 3i)³ in the form a ...
3      ### question: Express (–√3 + √–2)(2√3 – i) in ...
4      ### question: Find the multiplicative inverse ...
                             ...
566    ### question: If A = [[-2], [4], [5]] and B = ...
567    ### question: Express the matrix B = [[2, -2, ...
568    ### question: If A = [[cosθ, sinθ], [-sinθ, co...
569    ### question: If A and B are symmetric matrice...
570    ### question: Let A=[[2,-1],[3,4]], B=[[5,2],[...
Length: 571, dtype: object

In [13]:
from transformers import AutoTokenizer

/home/black_tree/Desktop/NLP project /.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [20]:
model_id = "google/gemma-2b"
tokeniser = AutoTokenizer.from_pretrained(model_id)
print("model loaded succesfully")

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: c5092ab4-7388-43bb-9e09-a7e409f1204c)')' thrown while requesting HEAD https://huggingface.co/google/gemma-2b/resolve/main/tokenizer_config.json
Retrying in 1s [Retry 1/5].

model loaded succesfully

In [21]:
prompt.iloc[0]

'### question: If 4x + i(3x – y) = 3 + i (– 6), where x and y are real numbers, then find the values of x and y.  ### answer: We have 4x + i (3x – y) = 3 + i (–6). Equating the real and the imaginary parts, we get 4x = 3 and 3x – y = – 6. On solving simultaneously, we get x = 3/4 and y = 33/4.'

In [35]:
def format(vec):
    x = vec[0]
    y = vec[1]
    z = f"<s><|user|>\n{x}</s><|assistant|>{y}</s>"
    return z

In [36]:
formatted_prompt = data.apply(format, axis=1)

/tmp/ipykernel_10167/3447999040.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  x = vec[0]
/tmp/ipykernel_10167/3447999040.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  y = vec[1]

In [37]:
formatted_prompt[0]

'<s><|user|>\nIf 4x + i(3x – y) = 3 + i (– 6), where x and y are real numbers, then find the values of x and y.</s><|assistant|>We have 4x + i (3x – y) = 3 + i (–6). Equating the real and the imaginary parts, we get 4x = 3 and 3x – y = – 6. On solving simultaneously, we get x = 3/4 and y = 33/4.</s>'

In [38]:
tokeniser.add_bos_token = "<s>"
tokeniser.add_eos_token = "</s>"

In [42]:
from datasets import Dataset

In [44]:
formatted_prompt = pd.DataFrame(formatted_prompt)

In [52]:
x = formatted_prompt.iloc[0]

In [ ]:
total_number = formatted_prompt.shape[0]
total_number

571

In [86]:
def tokenise(formatted_prompt, tokeniser):
    tokenised_prompt = []
    for p in range(len(formatted_prompt)):

        string_prompt = str(formatted_prompt.iloc[p])
        output_prompt = tokeniser(string_prompt)
        tokenised_prompt.append(output_prompt)
    return tokenised_prompt

In [87]:
tokenised_promot = tokenise(formatted_prompt, tokeniser)

In [91]:
tokenised_promot=pd.DataFrame(tokenised_promot)

In [92]:
tokenised_promot.to_pickle("/home/black_tree/Desktop/NLP project /tokenised_prompt.pkl")